### ISSUE TITLE
Update your documentation 

### ISSUE THREAD

**Issue by bhekor** [nuxt-community/firebase-module#641]
I just wasted like 20mins trying to debug this;

Your documentation mentioned using the latest and suggested this below
`npm install firebase@^8` which is not working with  `"@nuxtjs/firebase": "^8.2.2"`,

so I kept getting the error
 
 ✖ Nuxt Fatal Error                                                                                 ││                                                                                                      ││   Error: Cannot find module 'firebase/compat/app'                                                    ││   Require stack:                                                                                     ││   -                                                                                                  ││   C:\Users\xxxx\OneDrive\Desktop\xxxxx\node_modules\@nuxtjs\firebase\lib\mo   ││   dule.js              

and the latest now is 9.17.2 

Please suggest using this `npm install firebase` instead for a beginner like me.

**Comment by lupas** [comment]
Thanks a lot for the hint., there was indeed a sentence remaining that mentioned using the latest Nuxt.

Fixed with:
https://github.com/nuxt-community/firebase-module/commit/ef2baf24e41f15e19f6e7bdaa49cceaf17527903

**This module does currently not support Nuxt 3.**
